RESTAURAR OBLEA 

SELECT COUNT(*) FROM TINSPECCION I , TFACTURAS  F 
 WHEREF.CODFACTU=I.CODFACTU
 AND CODCOFAC IS NULL 
 AND  I.NUMOBLEA=''
/
SELECT COUNT(*) FROM  T_ERVTV_ANULAC WHERE NUMOBLEA=
/
SELECT COUNT(*) FROM T_ERVTV_INUTILIZ  I WHERE  I.OBLEAANT=
/
SELECT 
UPDATE  TOBLEAS O
SET ESTADO='S', o.FECHA_CONSUMIDA=NULL,o.CODINSPE=NULL
WHERE NUMERO=''
/


