CREATE TABLE CABA.TTMP_DEVOLUCIONSUVTV
(
  PAGOID   NUMBER(8),
  PATENTE  VARCHAR2(8 BYTE),
  BANCO    VARCHAR2(20 BYTE),
  CUENTA   VARCHAR2(50 BYTE),
  CBU      VARCHAR2(50 BYTE),
  CUIT     VARCHAR2(20 BYTE),
  TITULAR  VARCHAR2(100 BYTE),
  MOTIVO   VARCHAR2(100 BYTE),
  MONTO    VARCHAR2(20 BYTE),
  PLANTA   VARCHAR2(30 BYTE),
  FECHA    VARCHAR2(12 BYTE)
)
TABLESPACE USER_DATA_ESTACION
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCACHE;
/
CREATE TABLE CABA.TTMP_PLADEVOLUCION
(
  DOMINIO        VARCHAR2(8 BYTE),
  PAGOID         VARCHAR2(12 BYTE),
  CODIGPAGO      VARCHAR2(20 BYTE),
  NOMBRE         VARCHAR2(100 BYTE),
  BENEFICIARIO   VARCHAR2(100 BYTE),
  OBSERVACIONES  VARCHAR2(100 BYTE),
  MONTO          VARCHAR2(10 BYTE),
  REVISO         VARCHAR2(1 BYTE),
  INSPECCION     VARCHAR2(1 BYTE),
  ENTIDAD        VARCHAR2(1 BYTE),
  FACTURA        VARCHAR2(100 BYTE),
  NC             VARCHAR2(100 BYTE)
)
TABLESPACE USER_DATA_ESTACION
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCACHE;
