	CREATE TABLE TCONTROLADORES_FISCALES
(
  CODIGO        NUMBER(4),
  CONTROLADOR   VARCHAR2(30 BYTE)                NOT NULL,
  IMPRIME_NC    VARCHAR2(2 BYTE)                 NOT NULL

)


insert into TCONTROLADORES_FISCALES values(1,'EPSON - TM2000 AF+','No'); 
insert into TCONTROLADORES_FISCALES values(2,'EPSON - TM2000','No');
insert into TCONTROLADORES_FISCALES values(3,'EPSON - TM2002','No');
insert into TCONTROLADORES_FISCALES values(4,'EPSON - TMU-220 AF II','No');
insert into TCONTROLADORES_FISCALES values(5,'EPSON - TMU950','No');





