select distinct 
TINSP.FECHALTA,
TFAC.codfactu Tfac_Codfactu, 
TDET.pagoid,
TDET.archivoenviado,
TDATT.dvdomino,
TINSP.codvehic,
TINSP.codinspe,
TDATT.tipoinspe,
TDATT.tipoturno,
TDATT.facturado,
TDATT.reviso,
TINSP.ejercici,
TINSP.INSPFINA,
TINSP.TIPO,
TINSP.resultad

FROM TINSPECCION TINSP
INNER JOIN Tinformacionpago TINFO on TINSP.CODVEHIC = TINFO.CODVEHICULO
INNER JOIN tdetallespago TDET on TDET.IDDETALLESPAGO = TINFO.IDDETALLESPAGO
INNER JOIN Tdatreserva TDAT on TDAT.IDDETALLESPAGO = TINFO.IDDETALLESPAGO
INNER JOIN Tfacturas TFAC on TFAC.IDDETALLESPAGO = TINFO.IDDETALLESPAGO
INNER JOIN TDATOSTURNOHISTORIAL TDATT on TDATT.PAGOIDVERIFICACION = TDET.pagoid

where TINSP.codfactu is null
and TINSP.INSPFINA = 'S'
and TINSP.tipo = 'A'
and ((TDAT.ESREVE = 'N' or TDAT.ESREVEDIA  = 'N') 
  OR (TDAT.ESREVE = 'N' AND TDAT.ESREVEDIA = 'N'))
and TDET.facturado = 'S'
AND TDATT.facturado NOT IN ('E','O')
and TDATT.TIPOTURNO <> 'EX'
and TDATT.CODINSPE = TINSP.CODINSPE
and TDATT.tipoinspe = 'P'
order by TINSP.fechalta asc;


BEGIN CABA.CORRIGECODFACTUTINSPECCION; COMMIT; END;



select distinct 
TINSP.FECHALTA,
TFAC.codfactu Tfac_Codfactu, 
TDET.pagoid,
TDET.archivoenviado,
TDATT.dvdomino,
TINSP.codvehic,
TINSP.codinspe,
TDATT.tipoinspe,
TDATT.tipoturno,
TDATT.facturado,
TDATT.reviso,
TINSP.ejercici,
TINSP.INSPFINA,
TINSP.TIPO,
TINSP.resultad

FROM TINSPECCION TINSP
INNER JOIN Tinformacionpago TINFO on TINSP.CODVEHIC = TINFO.CODVEHICULO
INNER JOIN tdetallespago TDET on TDET.IDDETALLESPAGO = TINFO.IDDETALLESPAGO
INNER JOIN Tdatreserva TDAT on TDAT.IDDETALLESPAGO = TINFO.IDDETALLESPAGO
INNER JOIN Tfacturas TFAC on TFAC.IDDETALLESPAGO = TINFO.IDDETALLESPAGO
INNER JOIN TDATOSTURNOHISTORIAL TDATT on TDATT.PAGOIDVERIFICACION = TDET.pagoid

where TINSP.codfactu is null
and TINSP.INSPFINA = 'S'
and TINSP.tipo = 'A'
and ((TDAT.ESREVE = 'N' or TDAT.ESREVEDIA  = 'N') 
  OR (TDAT.ESREVE = 'N' AND TDAT.ESREVEDIA = 'N'))
and TDET.facturado = 'S'
AND TDATT.facturado NOT IN ('E','O')
and TDATT.TIPOTURNO <> 'EX'
and TDATT.CODINSPE = TINSP.CODINSPE
and TDATT.tipoinspe = 'P'
order by TINSP.fechalta asc;


BEGIN CABA.CORRIGECODFACTUTINSPECCION; COMMIT; END;



