SELECT TO_CHAR(fechcons,'DD/MM/YYYY') FECHA, COUNT(*) AS Obleas
  FROM VTV_OBLEAS INNER JOIN PLANTAS P ON VTV_OBLEAS.IDPLANTA = P.IDPLANTA
 WHERE fechcons BETWEEN '01/05/2018' AND '31/05/2018'
   AND (P.IDZONA||P.NROPLANTA) = 21
GROUP BY fechcons ORDER BY 1;
--

SELECT TO_CHAR(c.fecha,'dd/mm/yyyy') Fecha, 
(c.CANTAPRR+c.CANTAPRV+c.CANTANULADAS+c.CANTINUTIL) Obleas, 
 c.CANTANULADAS Anuladas, 
 c.CANTINUTIL Inutilizadas
  FROM VTV_DATOS_CD c 
 WHERE c.FECHA BETWEEN '01/05/2018' AND '31/05/2018'
   AND (c.zona||c.planta) = 21
ORDER BY c.fecha asc;

--Reviso el dia con la diferencia.
SELECT VTV.*
FROM VTV_OBLEAS VTV INNER JOIN PLANTAS P ON VTV.IDPLANTA = P.IDPLANTA
WHERE fechcons BETWEEN '08/03/2018' AND '08/03/2018' 
AND (P.IDZONA||P.NROPLANTA) = 21  
--AND estado = 'K'
