unit UCtesFields;

interface

resourcestring
     FIELD_NombreYApellidos = 'NombreYApellidos';
     FIELD_TIPODOCU = 'TIPODOCU';
     FIELD_DOCUMENT = 'DOCUMENT';

     FIELD_ZONA     = 'ZONA';
     FIELD_ESTACION = 'ESTACION';
     FIELD_NCERTGNC = 'NCERTGNC';
     FIELD_ANIOFABR = 'ANIOFABR';
     FIELD_EJERCICI = 'EJERCICI';
     FIELD_CODINSPE = 'CODINSPE';
     FIELD_TIPO     = 'TIPO';
     FIELD_PATENTEN = 'PATENTEN';
     FIELD_PATENTEA = 'PATENTEA';
     FIELD_NUMBASTI = 'NUMBASTI';
     FIELD_NUMMOTOR = 'NUMMOTOR';
     FIELD_FECVENCI = 'FECVENCI';
     FIELD_ABRCLASI = 'ABRCLASI';
     FIELD_CODFRECU = 'CODFRECU';
     FIELD_TIPOESPE = 'TIPOESPE';
     FIELD_TIPODEST = 'TIPODEST';
     FIELD_CODMARCA = 'CODMARCA';
     FIELD_CODMODEL = 'CODMODEL';
     FIELD_RESULTAD = 'RESULTAD';
     FIELD_NOMTIPVE = 'NOMTIPVE';
     FIELD_NOMMARCA = 'NOMMARCA';
     FIELD_NOMMODEL = 'NOMMODEL';
     FIELD_TIPOVEHI = 'TIPOVEHI';
     FIELD_FECHALTA = 'FECHALTA';
     FIELD_HORFINAL = 'HORFINAL';
     FIELD_HORENTZ1 = 'HORENTZ1';
     FIELD_HORENTZ2 = 'HORENTZ2';
     FIELD_HORENTZ3 = 'HORENTZ3';
     FIELD_HORSALZ1 = 'HORSALZ1';
     FIELD_HORSALZ2 = 'HORSALZ2';
     FIELD_HORSALZ3 = 'HORSALZ3';
     FIELD_IDENCONC = 'IDENCONC';
     FIELD_NOMRESPO = 'NOMRESPO';
     FIELD_NUMREVZ1 = 'NUMREVZ1';
     FIELD_NUMREVZ2 = 'NUMREVZ2';
     FIELD_NUMREVZ3 = 'NUMREVZ3';
     FIELD_NUMLINZ1 = 'NUMLINZ1';
     FIELD_NUMLINZ2 = 'NUMLINZ2';
     FIELD_NUMLINZ3 = 'NUMLINZ3';
     FIELD_MATRICUL = 'MATRICUL';
     FIELD_NUMEJES  = 'NUMEJES';
     FIELD_FECMATRI = 'FECMATRI';
     FIELD_ERROR    = 'ERROR';
     FIELD_TIPOGAS  = 'TIPOGAS';
     FIELD_TIPFACTU = 'TIPFACTU';
     FIELD_TIPTRIBU = 'TIPTRIBU';
     FIELD_CREDITCL = 'CREDITCL';

     FIELD_SINDATOS = 'SINDATOS';
     FIELD_CODCLIEN = 'CODCLIEN';
     FIELD_FORMPAGO = 'FORMPAGO';
     FIELD_IVAINSCR = 'IVAINSCR';
     FIELD_IVANOINS = 'IVANOINS';
     FIELD_IMPONETO = 'IMPONETO';
     FIELD_NUMFACTU = 'NUMFACTU';

     FIELD_CODVEHIC = 'CODVEHIC';
     FIELD_CODCLPRO = 'CODCLPRO';
     FIELD_CODCLCON = 'CODCLCON';
     FIELD_CODCLTEN = 'CODCLTEN';
     FIELD_INSPFINA = 'INSPFINA';
     FIELD_IMPRESA  = 'IMPRESA';
     FIELD_CODFACTU = 'CODFACTU';
     FIELD_TARIBASI = 'TARIBASI';
     FIELD_PORCREVI = 'PORCREVI';

     FIELD_ESTADO   = 'ESTADO';
     FIELD_HORAINIC = 'HORAINIC';
     FIELD_PRECIOUNITARIO = 'PRECIOUNITARIO';

     FIELD_CODCOFAC = 'CODCOFAC';
     FIELD_ROWID    = 'ROWID';
     FIELD_REVERIFI = 'REVERIFI';
     FIELD_ApellidosYNombre = 'ApellidosYNombre';
     FIELD_APELLID2 = 'APELLID2';
     FIELD_APELLID1 = 'APELLID1';
     FIELD_NOMBRE   = 'NOMBRE';
     FIELD_FECMOROS = 'FECMOROS';
     FIELD_TARIFAVE = 'TARIFAVE';
     FIELD_DIRECCIO = 'DIRECCIO';
     FIELD_CODPOSTA = 'CODPOSTA';
     FIELD_LOCALIDA = 'LOCALIDA';
     FIELD_CUIT_CLI = 'CUIT_CLI';

TABLA_VEHICULOS = 'TVEHICULO';
TABLA_INSPECCION = 'TINSPECCION';


     
implementation

end.
 