unit USTOCKESTACION;

interface

    uses
        DBTables,
        Graphics,
        USTOCKDATA;
    var
        BaudRate,PortNumber: string;

    const

        // NOMBRES DE COLUMNAS DE TABLAS DEL SISTEMA
        DATOS_PLANTAS = 'PLANTAS';
        DATOS_EMPRESAS = 'EMPRESAS';
        DATOS_PROVEEDORES = 'PROVEEDORES';
        DATOS_LOCALIDAD_INTERIOR = 'LOCALIDAD_INTERIOR';
        DATOS_CODPOSTA_INTERIOR = 'CODPOSTA_INTERIOR';
        DATOS_CODPOSTA_CAPITAL = 'CODPOSTA_CAPITAL';
        DATOS_PROVINCIAS = 'PROVINCIAS';
        DATOS_MOVIMIENTOS = 'MOVIMIENTOS';
        DATOS_OBLEAS = 'OBLEAS';
        DATOS_COLORES = 'COLORES';
        DATOS_PERSONAL = 'PERSONAL';
        DATOS_MOVIMIENTOS_VTV = 'VTV_MOVIMIENTO';
        DATOS_ZONAS = 'TZONAS';
        DATOS_MOVIMIENTOS_INFORME= 'MOV_INFORME';
        DATOS_INFOR_CERTIF= 'INFOR_CERTIF';

        // TABLAS DEL SISTEMA
        FIELD_IDPLANTA = 'IDPLANTA';
        FIELD_NOMBRE = 'NOMBRE';
        FIELD_FECHALTA = 'FECHALTA';
        FIELD_IDZONA = 'IDZONA';
        FIELD_IDEMPRESA = 'IDEMPRESA';
        FIELD_NROPLANTA = 'NROPLANTA';
        FIELD_CODTALLER = 'CODTALLER';
        FIELD_CALLE = 'CALLE';
        FIELD_NUMERO = 'NUMERO';
        FIELD_PISO = 'PISO';
        FIELD_DEPTO = 'DEPTO';
        FIELD_IDLOCALIDAD = 'IDLOCALIDAD';
        FIELD_IDPROVINCIA = 'IDPROVINCIA';
        FIELD_TELEFONO = 'TELEFONO';
        FIELD_JEFEPLANTA = 'JEFEPLANTA';
        FIELD_DESCRIPCION = 'DESCRIPCION';
        FIELD_RSOCIAL = 'RSOCIAL';
        FIELD_CUIT = 'CUIT';
        FIELD_IIBB = 'IIBB';
        FIELD_FECHINIACT = 'FECHINIACT';
        FIELD_IDPROVEEDOR = 'IDPROVEEDOR';
        FIELD_CODPOSTA = 'CODPOSTA';
        FIELD_EMAIL = 'EMAIL';
        FIELD_WEB = 'WEB';
        FIELD_TIPTRIBU = 'TIPTRIBU';
        FIELD_CONTACTO = 'CONTACTO';
        FIELD_IDCODPOSTA = 'IDCODPOSTA';
        FIELD_LOCALIDAD = 'LOCALIDAD';
        FIELD_CODPROVI = 'CODPROVI';
        FIELD_DESPROVI = 'DESPROVI';
        FIELD_IDMOVIMIENTO = 'IDMOVIMIENTO';
        FIELD_CANTIDAD = 'CANTIDAD';
        FIELD_OBLEAINICIAL = 'OBLEAINICIAL';
        FIELD_OBLEAFINAL = 'OBLEAFINAL';
        FIELD_IDORIGEN = 'IDORIGEN';
        FIELD_IDDESTINO = 'IDDESTINO';
        FIELD_TIPO = 'TIPO';
        FIELD_ANULADO = 'ANULADO';
        FIELD_NROCOMPROBANTE = 'NROCOMPROBANTE';
        FIELD_MOTIVO = 'MOTIVO';
        FIELD_IDOBLEA = 'IDOBLEA';
        FIELD_ANO = 'ANO';
        FIELD_IDEMPRESAORIGEN = 'IDEMPRESAORIGEN';
        FIELD_ESTADO = 'ESTADO';
        FIELD_COLOR = 'COLOR';
        FIELD_NOMBRE_Y_APELLIDOS = 'NombreYApellidos';
        FIELD_APELLIDO = 'APELLIDO';
        FIELD_CANTTARJAMA = 'CANTTARJAMA';
        FIELD_CANTETIQGNC = 'CANTETIQGNC';
        FIELD_CANTBOLSI = 'CANTBOLSI';
        FIELD_ZONA = 'ZONA';
        FIELD_PLANTA = 'PLANTA';
        FIELD_CANTCERTIF = 'CANTCERTIF';
        FIELD_CERTFINAL = 'CERTFINAL';

        PREVISUALIZAR = 'PREVIEW';
        IMPRIMIR = 'PRINT';

        TIPO_PANEL = 'PANEL';
        TIPO_PAGE = 'PAGE';
        TIPO_COMBO = 'COMBO';
        TIPO_DBEDIT = 'DBEDIT';

        //TIPOS DE MOVIMIENTOS
        MOV_TIPO_ENTRADA = 'E';
        MOV_TIPO_MOVIMIENTO = 'M';
        MOV_TIPO_TRANSFERENCIA = 'T';
        MOV_TIPO_EXTRAZONA = 'X';
        MOV_TIPO_DEVOLUCION = 'D';        

        //TIPOS DE LISTADOS
        L_TIPO_VTV = 'VTV';
        L_TIPO_GNC = 'GNC';

    type
        tTipoDocumento = (ttdDNI, ttdNIF, ttdCIF, ttdNull);
        TTagSet = set of 1..10;

implementation


end.
