unit UGLOBAL;

interface
VAR
ID_PLANTILLA_MODIFICA:LONGINT;
BASE:STRING;
USUARIO_BASE:STRING;
DATASOURCE_BASE:STRING;
USUARIO_CONECTADO:STRING;
ID_EMPRESA:STRING;
ID_PLANTA:STRING;
OPCION_DE_GESTION:LONGINT;
VALOR_BUSQUEDA_GESTION:STRING;
OPCION_FORMULARIO:STRING;
FECHA_DESDE_ORIGINAL,FECHA_HASTA_ORIGINAL:STRING;
NUMERO_PLANILLA_MODIFICA:LONGINT;
ID_USUARIO_CONECTADO:LONGINT;
TIPO_USUARIO_CONECTADO:longint;

implementation

end.
