CREATE TABLE FACTURACIONBANCO
(
  PATENTE   VARCHAR2(20),
  PAGOID    VARCHAR2(20),
  MONTO     VARCHAR2(20),
  Dato4     VARCHAR2(30),
  Dato5     VARCHAR2(10),
  Dato6     VARCHAR2(20),
  Dato7     VARCHAR2(20)
) 
TABLESPACE USER_DATA_ESTACION
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCACHE;


CREATE INDEX INDX_FACBANCOPATENTE ON FACTURACIONBANCO
(PATENTE)
LOGGING
TABLESPACE INDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

CREATE INDEX INDX_FACBANCOPAGO ON FACTURACIONBANCO
(PAGOID)
LOGGING
TABLESPACE INDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );
